config/routes.rb
Rails.application.routes.draw do
  root 'home#show'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  
  resources :coupons

  resources :blogs

  resources :contacts

  resources :checkout

  resources :profile 


  resources :users do
    collection do
      post 'subscribe'
    end
  end

  resources :wishlist

  resources :categories

   resources :carts do
    member do
      post 'add' => "carts#add_quantity", as: "add_quantity"
      post 'minus' => "carts#dec_quantity", as: "dec_quantity"
    end
  end

  resources :addresses

  resources :orders do
    collection do
      post 'track'
    end
  end

  resources :home 
  
  resources :payment do
    collection do
      post 'stripe_payment'
      get 'stripe_paymet_success'
      get 'cod'
    end
  end

  resources :products
  
  resources :shop

end
 

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.superadmin_role?
      can :manage, :all
      can :access, :rails_admin  # only admin can access Rails Admin
      can :manage, :dashboard    # allow access to dashboard
    end

    if user.supervisor_role?
      can :manage, User
      # Define abilities for the user here. For example:
      #   return unless user.present?
      #   can :read, :all
      #   return unless user.admin?
      #   can :manage, :all
      # The first argument to `can` is the action you are giving the user
      # permission to do.
      # If you pass :manage it will apply to every action. Other common actions
      # here are :read, :create, :update and :destroy.
      # The second argument is the resource the user can perform the action on.
      # If you pass :all it will apply to every resource. Otherwise pass a Ruby
      # class of the resource.
      # The third argument is an optional hash of conditions to further filter the
      # objects.
      # For example, here the user can only update published articles.
      #   can :update, Article, published: true
      # See the wiki for details:
      # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories, dependent: :destroy
  has_many :products, through: :product_categories, dependent: :destroy
  has_many :subcategories, class_name: 'Category', foreign_key: 'parent_id', dependent: :destroy
  belongs_to :parent_category, class_name: 'Category', optional: true
end

app/models/cm.rb
class Cm < ApplicationRecord
end

app/models/configuration.rb
class Configuration < ApplicationRecord
end

app/models/contact_u.rb
class ContactU < ApplicationRecord
  validates_presence_of :name, :message, :email
  validates :contact_no, presence: true, numericality: true, length: { minimum: 10, maximum: 12 }
  belongs_to :user
  after_save :contact_mail
  after_update :contact_update_mail
  def contact_mail
    UserMailer.contact_mail(self).deliver
  end

  def contact_update_mail
    UserMailer.contact_update_mail(self).deliver
  end
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  has_many :coupons_useds, dependent: :destroy
  has_many :users, through: :coupons_useds
end

app/models/coupons_used.rb
class CouponsUsed < ApplicationRecord
  belongs_to :user
  belongs_to :coupon
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :user_order
  belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_images, dependent: :destroy
  has_many :product_attribute_assocs, dependent: :destroy
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories, dependent: :destroy
  has_many :user_wish_lists, dependent: :destroy
  has_many :users, through: :user_wish_lists
  has_many :order_details, dependent: :destroy
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  has_one_attached :image
end

app/models/report.rb
class Report < ApplicationRecord
  def sales_report
    UserOrder.all.size
  end

  def customer_registered
    User.all.size
  end

  def coupons_used
    CouponsUsed.all.size
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, format: { with: /[a-z0-9]+@[a-z]+\.[a-z]{2,3}/, message: 'Please enter valid email' }
  after_create :welcome_send
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2 github]
  has_many :coupons_useds, dependent: :destroy
  has_many :user_addresses, dependent: :destroy
  has_many :contact_us, dependent: :destroy
  has_many :coupons, through: :coupons_useds, dependent: :destroy
  has_many :user_orders, dependent: :destroy
  has_many :user_wish_lists, dependent: :destroy
  has_many :products, through: :user_wish_lists

  def self.from_omniauth(response)
    User.find_or_create_by(uid: response[:uid], provider: response[:provider]) do |u|
      u.email = response[:info][:email]
      u.password = Devise.friendly_token[0, 20]
    end
  end

  def welcome_send
    UserMailer.welcome_send(self).deliver
    UserMailer.admin_mail(self).deliver
  end
end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  has_many :user_order
  belongs_to :user
end

app/models/user_order.rb
class UserOrder < ApplicationRecord
  after_update :status_mail
  belongs_to :user
  belongs_to :user_address
  has_many :order_details, dependent: :destroy
  has_many :products, through: :order_details
  enum status: { ordered: 0, shipped: 1, delivered: 2 }
  def status_mail
    if status == 'shipped' || status == 'delivered'
      UserMailer.status_mail(status).deliver
    end
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def index
    @checkout_total = session[:totals] if session[:totals].present?
    @address = current_user.user_addresses.last
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/checkout/_form.html.erb
<%= form_with model: @useraddress, url: addresses_path,remote: true, method: :post do |form| %>
<div class="row">
	<div class="col-sm-2"></div>
	<div class="col-sm-4">
		<%= form.label :first_Name %><br>
		<%= form.text_field :first_name ,type: "text",title: "only letters are allowed", pattern: "[A-Za-z]{1,32}", required: true%><br>
		<%= form.label :Last_Name %><br> 
		<%= form.text_field :Last_name,type: "text",title: "only letters are allowed", pattern: "[A-Za-z]{1,32}", required: true %><br>
		<%= form.label :mobile_no %><br> 
		<%= form.number_field :mobile_no, type: "text",pattern: "[1-9]{1}[0-9]{9}",title: "mobile no should be of 10 digits"%><br> 
		<div class="select_class checkout-spacing">
			<%= form.label :Country %>
			<br><%= form.select :Country, options_for_select( [['SELECT','SELECT'],['INDIA','INDIA'],['BRAZIL','BRAZIL'],['RASSIA','RASSIA'],['AMERICA','AMERICA']])%><br> <br>
		</div>
	</div>
	<div class="col-sm-4">
		<%= form.label :email %><br> 
		<%= form.email_field :email,pattern:"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$", type: "text" ,require:true%><br>
		<%= form.label :Pin_code %><br> 
		<%= form.number_field :pin_code, pattern: "[0-9]{6}", type: "text", title: "should be 6 of digits"%><br> 
		<%= form.label :Alternate_mobile_no%><br> 
		<%= form.number_field :Alternate_mobile_no, type: "text",pattern: "[1-9]{1}[0-9]{9}",title: "mobile no should be of 10 digits"%><br>
		<div class="select_class checkout-spacing">
			<%= form.label :State %><br>
			<%= form.select :State, options_for_select( [['SELECT','SELECT'],['MAHARASHTRA','MAHARASHTRA'],['GOA','GOA'],['DELHI','DELHI'],['PANJAB','PANJAB']])%><br>  
		</div>
	</div>
</div>
<div class="wid">
	<%= form.label :Address %><br>
	<%= form.text_field :Address %><br>
</div><br>
<div class="actions form-alignment">
	<%= form.submit %><br><br>
</div>
</div>	
<% end %>
</div>
</div>

app/views/checkout/cod.html.erb
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
  </head>
    <style>
      body {
        text-align: center;
        padding: 40px 0;
        background: #EBF0F5;
      }
        h1 {
          color: #88B04B;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-weight: 900;
          font-size: 40px;
          margin-bottom: 10px;
        }
        p {
          color: #404F5E;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-size:20px;
          margin: 0;
        }
      i {
        color: #9ABC66;
        font-size: 100px;
        line-height: 200px;
        margin-left:-15px;
      }
      .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 0 auto;
      }
    </style>
    <body>
      <div class="card">
      <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
      </div>
      <div><h1>$<%= @value %></h1></div>
     <div>Order_id:-<%= @user_order.id %></div>
      <div><%  @user = current_user %></div>
      <div><%= @user.email %>
        <h1>Order has been placed</h1> 
         <h4><%= button_to "okay", shop_index_path %></h4>
      </div>
    </body>
</html>


   

app/views/checkout/index.html.erb
<body>
	<section class="main-page-padding">
		<br><div>
			<input type="radio">
			<% if @address.present? %>
				<%= @address.Address %>,
				<%= @address.State %>,
				<%= @address.Country %>,
				<%= @address.pin_code %>,
				<%= @address.mobile_no %>
			<%end%>
		</div><br>
 		<div><input type="submit" name="change" value="Change Address" onclick="myFunction();" ></div><br>
			<div class=" backimg " id="myDIV"><h2 class="vh-100 form-alignment">Checkout Form</h2>
			<%= render :partial => 'form.html.erb'%>
			</div><br>
			<div class="container">
			<div class="row">
			<div class="col-sm-6">
			<h2 class="text-center mb-3">Review</h2>
				<tbody>
						<tr>
							<td colspan="4">&nbsp;</td>
							<td colspan="2">
								<table class="table table-condensed total-result">
									<tr>
										<td>Total</td>
										<td><span class="price-symbol">₹</span><%= @checkout_total.to_i %></td>
									</tr>
								</table>
							</td>
						</tr>
				</tbody>
			</div>
		<div class="col-sm-6 text-center mb-3">
			<h2 class="text-center mb-3">Payment</h2><br>
		<div class="width">
			<%= button_to "COD",cod_payment_index_path, method: :get %><br>
			<%= button_to "Stripe",stripe_payment_payment_index_path(final_amount: @checkout_total ) %></div>
		</div>
	</div>
	</section> 
</section>
<script>
function myFunction() {
  var x = document.getElementById("myDIV");
  if (x.style.display === "none") {
    x.style.display = "block";
  } 
  else {
    x.style.display = "none";
  }
}
</script>
</body>
</html>

app/views/checkout/show.html.erb
<script>
var stripe = Stripe(
  "pk_test_51MD3qeSA33xedoICWGqzUb9rvgFVipYiW57epwquiLFA4oKZbhKGFf1UxVVEYsJ4HiiRrhELtNkOd24Bfv5UfT0M00LNp28wdM");
stripe.redirectToCheckout({sessionId: "<%= @session.id %>"}).then(function (result) {});    
</script>