config/routes.rb
Rails.application.routes.draw do
  root 'home#show'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  
  resources :coupons

  resources :blogs

  resources :contacts

  resources :checkout

  resources :profile 


  resources :users do
    collection do
      post 'subscribe'
    end
  end

  resources :wishlist

  resources :categories

   resources :carts do
    member do
      post 'add' => "carts#add_quantity", as: "add_quantity"
      post 'minus' => "carts#dec_quantity", as: "dec_quantity"
    end
  end

  resources :addresses

  resources :orders do
    collection do
      post 'track'
    end
  end

  resources :home 
  
  resources :payment do
    collection do
      post 'stripe_payment'
      get 'stripe_paymet_success'
      get 'cod'
    end
  end

  resources :products
  
  resources :shop

end
 

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.superadmin_role?
      can :manage, :all
      can :access, :rails_admin  # only admin can access Rails Admin
      can :manage, :dashboard    # allow access to dashboard
    end

    if user.supervisor_role?
      can :manage, User
      # Define abilities for the user here. For example:
      #   return unless user.present?
      #   can :read, :all
      #   return unless user.admin?
      #   can :manage, :all
      # The first argument to `can` is the action you are giving the user
      # permission to do.
      # If you pass :manage it will apply to every action. Other common actions
      # here are :read, :create, :update and :destroy.
      # The second argument is the resource the user can perform the action on.
      # If you pass :all it will apply to every resource. Otherwise pass a Ruby
      # class of the resource.
      # The third argument is an optional hash of conditions to further filter the
      # objects.
      # For example, here the user can only update published articles.
      #   can :update, Article, published: true
      # See the wiki for details:
      # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories, dependent: :destroy
  has_many :products, through: :product_categories, dependent: :destroy
  has_many :subcategories, class_name: 'Category', foreign_key: 'parent_id', dependent: :destroy
  belongs_to :parent_category, class_name: 'Category', optional: true
end

app/models/cm.rb
class Cm < ApplicationRecord
end

app/models/configuration.rb
class Configuration < ApplicationRecord
end

app/models/contact_u.rb
class ContactU < ApplicationRecord
  validates_presence_of :name, :message, :email
  validates :contact_no, presence: true, numericality: true, length: { minimum: 10, maximum: 12 }
  belongs_to :user
  after_save :contact_mail
  after_update :contact_update_mail
  def contact_mail
    UserMailer.contact_mail(self).deliver
  end

  def contact_update_mail
    UserMailer.contact_update_mail(self).deliver
  end
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  has_many :coupons_useds, dependent: :destroy
  has_many :users, through: :coupons_useds
end

app/models/coupons_used.rb
class CouponsUsed < ApplicationRecord
  belongs_to :user
  belongs_to :coupon
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :user_order
  belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_images, dependent: :destroy
  has_many :product_attribute_assocs, dependent: :destroy
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories, dependent: :destroy
  has_many :user_wish_lists, dependent: :destroy
  has_many :users, through: :user_wish_lists
  has_many :order_details, dependent: :destroy
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  has_one_attached :image
end

app/models/report.rb
class Report < ApplicationRecord
  def sales_report
    UserOrder.all.size
  end

  def customer_registered
    User.all.size
  end

  def coupons_used
    CouponsUsed.all.size
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, format: { with: /[a-z0-9]+@[a-z]+\.[a-z]{2,3}/, message: 'Please enter valid email' }
  after_create :welcome_send
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2 github]
  has_many :coupons_useds, dependent: :destroy
  has_many :user_addresses, dependent: :destroy
  has_many :contact_us, dependent: :destroy
  has_many :coupons, through: :coupons_useds, dependent: :destroy
  has_many :user_orders, dependent: :destroy
  has_many :user_wish_lists, dependent: :destroy
  has_many :products, through: :user_wish_lists

  def self.from_omniauth(response)
    User.find_or_create_by(uid: response[:uid], provider: response[:provider]) do |u|
      u.email = response[:info][:email]
      u.password = Devise.friendly_token[0, 20]
    end
  end

  def welcome_send
    UserMailer.welcome_send(self).deliver
    UserMailer.admin_mail(self).deliver
  end
end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  has_many :user_order
  belongs_to :user
end

app/models/user_order.rb
class UserOrder < ApplicationRecord
  after_update :status_mail
  belongs_to :user
  belongs_to :user_address
  has_many :order_details, dependent: :destroy
  has_many :products, through: :order_details
  enum status: { ordered: 0, shipped: 1, delivered: 2 }
  def status_mail
    if status == 'shipped' || status == 'delivered'
      UserMailer.status_mail(status).deliver
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shop/_footer.html.erb
<footer id="footer"><!--Footer-->
		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="companyinfo">
							<h2><span>e</span>-shopper</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
						</div>
					</div>
					<div class="col-sm-7">
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<%= image_tag("home/iframe1.png", alt: "") %>
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<%= image_tag("home/iframe2.png", alt: "") %>
										
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<%= image_tag("home/iframe3.png", alt: "") %>
								
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<%= image_tag("home/iframe4.png", alt: "") %>
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="address">
							<img src="images/home/map.png" alt="" />
							<p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Service</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Online Help</a></li>
								<li><a href="#">Contact Us</a></li>
								<li><a href="#">Order Status</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Quock Shop</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">T-Shirt</a></li>
								<li><a href="#">Mens</a></li>
								<li><a href="#">Womens</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Policies</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Terms of Use</a></li>
								<li><a href="#">Privecy Policy</a></li>
								<li><a href="#">Refund Policy</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Company Information</a></li>
								<li><a href="#">Careers</a></li>
								<li><a href="#">Store Location</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							 <h2>About Shopper</h2>
								<%if user_signed_in? %>
									<%= form_with url: mailchimp_home_index_path,  local: true do |form| %>
									<%= form.hidden_field :email, :value=> current_user.email %>
									<div class="actions">
										<div style="margin-left:0px;">
											<b><%= form.submit "Subscribed" %></b>
										</div>
									</div>
									<% end %>
								<%end%>
								<br><p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
					<p class="pull-right">Designed by <span><a target="_blank" href="http://www.avdhut.com">Avdhut</a></span></p>
				</div>
			</div>
		</div>
		
	</footer><!--/Footer-->


  <%= javascript_include_tag"js/main.js" %>
  <%= javascript_include_tag"js/bootstrap.min.js" %>
  <%= javascript_include_tag"js/jquery.scrollUp.min.js" %>
  <%= javascript_include_tag"js/jquery.prettyPhoto.js" %>
  <%= javascript_include_tag"js/jquery.js" %>

app/views/shop/blog.html.erb
<body>	
	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						
						<div class="shipping text-center"><!--shipping-->
							<%= image_tag("home/shipping.jpg", alt: "") %>
						</div><!--/shipping-->
					</div>
				</div>
				<div class="col-sm-9">
					<div class="blog-post-area">
						<h2 class="title text-center">Latest From our Blog</h2>
						<div class="single-blog-post">
							<h3>Girls Pink T Shirt arrived in store</h3>
							<div class="post-meta">
								
								<span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								</span>
							</div>
							<a href="">
								<%= image_tag("blog/blog-one.jpg", alt: "") %>
								<!-- <img src="images/blog/blog-one.jpg" alt=""> -->
							</a>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
						
						</div>
						<div class="single-blog-post">
							<h3>Girls Pink T Shirt arrived in store</h3>
							<div class="post-meta">
								
								<span>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star-half-o"></i>
								</span>
							</div>
							<a href="">
								<%= image_tag("blog/blog-two.jpg", alt: "") %>
								<!-- <img src="images/blog/blog-two.jpg" alt=""> -->
							</a>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
						
						</div>
						<div class="single-blog-post">
							<h3>Girls Pink T Shirt arrived in store</h3>
							<div class="post-meta">
								
								<span>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star-half-o"></i>
								</span>
							</div>
							<a href="">
								<%= image_tag("blog/blog-three.jpg", alt: "") %>
								<!-- <img src="images/blog/blog-three.jpg" alt=""> -->
							</a>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
							
						</div>
						<div class="pagination-area">
							
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	
</body>
</html>

app/views/shop/cart.html.erb
<body>
	<section id="cart_items">
		<div class="container hey">
			<% if @cart.product.present? %>
			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Item</td>
							<td class="image">Product_Image</td>
							<td class="price">Price</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total</td>
							<td ></td>
						</tr>
					</thead>

					<tbody>
						<% @product_price_lists = [] %>
						<% @cart.each do |product| %>
							<tr>
								<td><h4 style="margin-left:20px"><%= product.name %></h4> </td>
								<td><%= link_to product_path(product) do%><%= image_tag(product.product_images.first.image,class:"thumbnaill")%><%end%></td>
								<td class="cart_price"><p>$<%= product.price %></p></td>
								<td class="quantity">
									<div class="cart_quantity_button">
									<%= link_to '+',add_quantity_path(product), method: :post, :remote => true,class: 'btn primary quantity cart_quantity_up'%>	
									<input id="target-for-change-<%= product.id %>"class="cart_quantity_input", name="quantity" value="<%= product.quantity %>"size="1">
									<%= link_to '-',dec_quantity_path(product), method: :post,remote: true, class: 'btn primary cart_quantity_up' %>

									</div>
								</td>
								<td class="cart_total">
									<p id="target-for-total-<%= product.id %>">$<%= tp = (product.price)*(product.quantity) %></p>
								</td>
								<td class="cart_delete"><br>
									<%=  button_to "X", remove_from_cart_path(product), method: :delete %>
								</td>
							</tr>
						<% end %>
					</tbody>
					
				</table>
			</div>
		</div>
	</section> <!--/#cart_items-->

	<section id="do_action">
		<div class="container">
			<div class="heading">
				<h3>What would you like to do next?</h3>
				<p>Choose if you have a discount code or reward points you want to use or would like to estimate your delivery cost.</p>
			
			</div>
			<div class="row">
				<div class="col-sm-6">
					<div class="chose_area">
						<ul class="user_option">
			
							<li >
						<%= form_with model: @coupon, url: shop_cart_path,  local:true  do |form| %>
						<ul class="user_option">
							<li>
							<div class="mb-3">
								<%= form.label :coupon_code %>
								<%= form.text_field :code, class: "form-control" , placeholder: "enter coupon code" %>
							</div>
								
							</li>
							<li>
							<div class="mb-3">
								<%= form.submit "Apply", class: "btn btn-primary" %>
							</div>
							<% if @mv.present? %>
               					 <p style="color: greenyellow;"><%= @msgg %>
           				   <% end %>
							</li>
						</ul>
						<% end %>
							</li>
						</ul>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="total_area">
						<ul>
							<li> Cart Total Price <span id="target-for-total-cart">$<%= @value %> </span></li>
							<li>Shipping Cost <span id="total-product-val">$<%= @shipping_cost %></span></li>
							<li>Total<span id="finall-vall">$<%= @f_value %><span></li>
							
							<% if @f_value == 0 %>
								<br><h6 style="color:red"><%= "please add the product in cart" %></h6>
							<%else%>
								<span class="btn btn-default check_out" href=""><%= link_to "Checkout", shop_checkout_path %> </span>
							<%end%>
							</ul>
					</div>
				</div>
			</div>
		</div>
	</section><!--/#do_action-->
	<%else%>
	 <%= image_tag("social/emptycart.png",class:"emptycart")%>  <br>
 <div style="margin-left:520px;"><button><%= link_to"shop",root_path%></button>
	<%end%></div>
</body>
</html>

app/views/shop/checkout.html.erb
<body><section class="hey"><div><input type="radio">
			<% if @address.present? %>
			<%= @address.Address %>,
			<%= @address.State %>,
			<%= @address.Country %>,
			<%= @address.pin_code %>,
			<%= @address.mobile_no %>
			<%end%>
		</div>
 <div><input type="submit" name="change" value="Update Address" onclick="myFunction();" ></div>
<div class=" backimg" id="myDIV" style="background-color:white;display: none;"><h2 class="vh-100 text1 ">Checkout Form</h2>
	<div class="container" >
	  	<%= form_with model: @useraddress, url:shop_create_path,remote: true, method: :post do |form| %>
					<div class="row">
						<div class="col-sm-2"></div>
						<div class="col-sm-4">
					<%= form.label :first_Name %><br>
					<%= form.text_field :first_name ,type: "text",title: "only letters are allowed", pattern: "[A-Za-z]{1,32}", required: true%><br>
					<%= form.label :Last_Name %><br> 
					<%= form.text_field :Last_name,type: "text",title: "only letters are allowed", pattern: "[A-Za-z]{1,32}", required: true %><br>
						<%= form.label :mobile_no %><br> 
					<%= form.number_field :mobile_no, type: "text",pattern: "[1-9]{1}[0-9]{9}",title: "mobile no should be of 10 digits"%><br> 
					<div class="select_class" style="width: 187px;">
							<%= form.label :Country %>
						<br><%= form.select :Country, options_for_select( [['SELECT','SELECT'],['INDIA','INDIA'],['BRAZIL','BRAZIL'],['RASSIA','RASSIA'],['AMERICA','AMERICA']])%><br> <br>
					</div>
				</div>
				<div class="col-sm-4">
					<%= form.label :email %><br> 
					<%= form.email_field :email,pattern:"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$", type: "text" ,require:true%><br>
					<%= form.label :Pin_code %><br> 
					<%= form.number_field :pin_code, pattern: "[0-9]{6}", type: "text", title: "should be 6 of digits"%><br> 
					<%= form.label :Alternate_mobile_no%><br> 
					<%= form.number_field :Alternate_mobile_no, type: "text",pattern: "[1-9]{1}[0-9]{9}",title: "mobile no should be of 10 digits"%><br>
					<div class="select_class" style="width: 187px;">
						<%= form.label :State %>
						<br><%= form.select :State, options_for_select( [['SELECT','SELECT'],['MAHARASHTRA','MAHARASHTRA'],['GOA','GOA'],['DELHI','DELHI'],['PANJAB','PANJAB']])%><br>  
					</div>
				</div>
			</div>
				<div class="wid">
					<%= form.label :Address %><br>
					<%= form.text_field :Address %><br>
				</div>
				</div>
					
				<div class="actions">
					<br><%= form.submit %><br><br> 
				</div>
				<% end %>
			</div>
		</div>
		</div><br>
	<div class="container">
		<div class="row">
			<div class="col-sm-6">
			<h2 class="text-center mb-3">Review</h2>
				<tbody>
						<tr>
							<td colspan="4">&nbsp;</td>
							<td colspan="2">
								<table class="table table-condensed total-result">
									<tr>
										<td>Cart Sub Total</td>
										<td>$<%= @value %></td>
									</tr>
									<tr>
										<td>Exo Tax</td>
										<td>-</td>
									</tr>
									<tr class="shipping-cost">
										<td>Shipping Cost</td>
										<td>$<%= @ship %></td>										
									</tr>
									<tr>
										<td>Total</td>
										<td><span>$<%= @value %></span></td>
									</tr>
								</table>
							</td>
						</tr>
					</tbody>
			</div>
		<div class="col-sm-6 text-center mb-3">
			<h2 class="text-center mb-3">Payment</h2><br><br>
		<div class="width">
			<%= button_to "Stripe",shop_stripe_path %><br></div>
			<div>
			<%= button_to "COD",shop_cod_path ,method: :get %>
		</div>
	</div>
</div>
</section> 
</section>
<script>
function myFunction() {
  var x = document.getElementById("myDIV");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}
</script>

</body>
</html>

app/views/shop/order.html.erb
    <div class="container hey">
<% if @orders.present?%>
<section id="cart_items ">
     
      <div class="table-responsive cart_info">
        <table class="table table-condensed">
          <thead>
            <tr class="cart_menu">
              <td class="image">Product image</td>
              <td class=name>Name</td>
              <td class="price">Price</td>
              <td>Qty</td>
              <td>Order_id</td>
            </tr>
          </thead>
          <tbody>
           <% @orders.each do |order| %>
               <% order.products.each do |product| %>
              <tr>
                <td><%= link_to product_path(product) do%><%= image_tag(product.product_images.first.image,class:"thumbnaill") %><%end%> </td>
                <td><h4><%= product.name %></h4></td>
                <td class="cart_price"><p>$<%= product.price %></p></td>
                <td ><p><%= product.quantity %></p></td>
                <td><h5><%= link_to shop_track_path(order)do%><%= order.id %><%end%></h5></td>
              </tr>
            <% end %>
            <% end %>
          </tbody>
          
        </table>
      </div>
      <% else %>
  <%= image_tag("social/order.jpeg",class:"emptycart")%>  <br>
 <div style="margin-left:520px;"><button><%= link_to"shop",root_path%></button>
  <%end%>
    </div>

  </section> 

app/views/shop/success.html.erb
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
  </head>
    <style>
      .bodyy {
        text-align: center;
        padding: 40px 0;
        background: #EBF0F5;
      }
        .h11 {
          color: #88B04B;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-weight: 900;
          font-size: 40px;
          margin-bottom: 10px;
        }
        .pp {
          color: #404F5E;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-size:20px;
          margin: 0;
        }
      .ii {
        color: #9ABC66;
        font-size: 100px;
        line-height: 200px;
        margin-left:-15px;
      }
      .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 0 auto;
      }
    </style>
    <body class="bodyy">
      <section class="hey">
      <div class="card">
      <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark ii">✓</i>
      </div>
      <div><h1 class="h11">$<%= @total %></h1></div>
      <div><%= @pay_id %></div>
      <div><%  @user = current_user %></div>
      <div><%= @user.email %>
        <h1>Success</h1> 
        <p class="pp">payment successfully Done</p>
         <h4><%= button_to "okay", root_path %></h4>
      </div>
    </div>
  </section>
    </body>
</html>


  