config/routes.rb
Rails.application.routes.draw do
  root 'home#show'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  
  resources :coupons

  resources :blogs

  resources :contacts

  resources :checkout

  resources :profile 


  resources :users do
    collection do
      post 'subscribe'
    end
  end

  resources :wishlist

  resources :categories

   resources :carts do
    member do
      post 'add' => "carts#add_quantity", as: "add_quantity"
      post 'minus' => "carts#dec_quantity", as: "dec_quantity"
    end
  end

  resources :addresses

  resources :orders do
    collection do
      post 'track'
    end
  end

  resources :home 
  
  resources :payment do
    collection do
      post 'stripe_payment'
      get 'stripe_paymet_success'
      get 'cod'
    end
  end

  resources :products
  
  resources :shop

end
 

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.superadmin_role?
      can :manage, :all
      can :access, :rails_admin  # only admin can access Rails Admin
      can :manage, :dashboard    # allow access to dashboard
    end

    if user.supervisor_role?
      can :manage, User
      # Define abilities for the user here. For example:
      #   return unless user.present?
      #   can :read, :all
      #   return unless user.admin?
      #   can :manage, :all
      # The first argument to `can` is the action you are giving the user
      # permission to do.
      # If you pass :manage it will apply to every action. Other common actions
      # here are :read, :create, :update and :destroy.
      # The second argument is the resource the user can perform the action on.
      # If you pass :all it will apply to every resource. Otherwise pass a Ruby
      # class of the resource.
      # The third argument is an optional hash of conditions to further filter the
      # objects.
      # For example, here the user can only update published articles.
      #   can :update, Article, published: true
      # See the wiki for details:
      # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories, dependent: :destroy
  has_many :products, through: :product_categories, dependent: :destroy
  has_many :subcategories, class_name: 'Category', foreign_key: 'parent_id', dependent: :destroy
  belongs_to :parent_category, class_name: 'Category', optional: true
end

app/models/cm.rb
class Cm < ApplicationRecord
end

app/models/configuration.rb
class Configuration < ApplicationRecord
end

app/models/contact_u.rb
class ContactU < ApplicationRecord
  validates_presence_of :name, :message, :email
  validates :contact_no, presence: true, numericality: true, length: { minimum: 10, maximum: 12 }
  belongs_to :user
  after_save :contact_mail
  after_update :contact_update_mail
  def contact_mail
    UserMailer.contact_mail(self).deliver
  end

  def contact_update_mail
    UserMailer.contact_update_mail(self).deliver
  end
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  has_many :coupons_useds, dependent: :destroy
  has_many :users, through: :coupons_useds
end

app/models/coupons_used.rb
class CouponsUsed < ApplicationRecord
  belongs_to :user
  belongs_to :coupon
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :user_order
  belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_images, dependent: :destroy
  has_many :product_attribute_assocs, dependent: :destroy
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories, dependent: :destroy
  has_many :user_wish_lists, dependent: :destroy
  has_many :users, through: :user_wish_lists
  has_many :order_details, dependent: :destroy
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  has_one_attached :image
end

app/models/report.rb
class Report < ApplicationRecord
  def sales_report
    UserOrder.all.size
  end

  def customer_registered
    User.all.size
  end

  def coupons_used
    CouponsUsed.all.size
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, format: { with: /[a-z0-9]+@[a-z]+\.[a-z]{2,3}/, message: 'Please enter valid email' }
  after_create :welcome_send
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2 github]
  has_many :coupons_useds, dependent: :destroy
  has_many :user_addresses, dependent: :destroy
  has_many :contact_us, dependent: :destroy
  has_many :coupons, through: :coupons_useds, dependent: :destroy
  has_many :user_orders, dependent: :destroy
  has_many :user_wish_lists, dependent: :destroy
  has_many :products, through: :user_wish_lists

  def self.from_omniauth(response)
    User.find_or_create_by(uid: response[:uid], provider: response[:provider]) do |u|
      u.email = response[:info][:email]
      u.password = Devise.friendly_token[0, 20]
    end
  end

  def welcome_send
    UserMailer.welcome_send(self).deliver
    UserMailer.admin_mail(self).deliver
  end
end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  has_many :user_order
  belongs_to :user
end

app/models/user_order.rb
class UserOrder < ApplicationRecord
  after_update :status_mail
  belongs_to :user
  belongs_to :user_address
  has_many :order_details, dependent: :destroy
  has_many :products, through: :order_details
  enum status: { ordered: 0, shipped: 1, delivered: 2 }
  def status_mail
    if status == 'shipped' || status == 'delivered'
      UserMailer.status_mail(status).deliver
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  def show
    @banners = BannerManagement.all
    @category = Category.where(parent_id: nil)
    @products = Product.all
    @prod_images = ProductImage.all
    @cms = Cm.last
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_footer.html.erb
	<footer id="footer"><!--Footer-->
		<div class="footer-top">
				<div class="row row-margin">
					<div class="col-sm-2">
						<div class="companyinfo">
							<h2><span>e</span>-shopper</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
						</div>
					</div>
					<div class="col-sm-7">
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<%= image_tag("home/iframe1.png", alt: "") %>
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<%= image_tag("home/iframe2.png", alt: "") %>
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<%= image_tag("home/iframe3.png", alt: "") %>
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<%= image_tag("home/iframe4.png", alt: "") %>
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="address">
							<%= image_tag("home/map.png", alt: "") %>
							<p></p>
						</div>
					</div>
			</div>
		</div>
		
		<div class="footer-widget">
				<div class="row row-margin">
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Service</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Online Help</a></li>
								<li><a href="#">Contact Us</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Quock Shop</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">T-Shirt</a></li>
								<li><a href="#">Mens</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Policies</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Terms of Use</a></li>
								<li><a href="#">Privecy Policy</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Company Information</a></li>
								<li><a href="#">Careers</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<h2>Mailchimp Subscription</h2><br>
							<%if user_signed_in? %>
									<%= form_with url:subscribe_users_path, local: true do |form| %>
									<%= form.hidden_field :email, :value=> current_user.email %>
									<div class="actions">
											<b><%= form.submit "Subscribe" %></b>
									</div>
									<% end %>
								<%end%>
						</div>
					</div>
				</div>
			</div>
		</div>




		<div class="footer-bottom">
			<div class="row row-margin">
				<p class="pull-left">Copyright © 2023 E-SHOPPER Inc. All rights reserved.</p>
				<p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Avdhut</a></span></p>
			</div>
		</div>
	</footer><!--/Footer-->

  <%= javascript_include_tag"js/main.js" %>
  <%= javascript_include_tag"js/bootstrap.min.js" %>
  <%= javascript_include_tag"js/jquery.scrollUp.min.js" %>
  <%= javascript_include_tag"js/jquery.prettyPhoto.js" %>
  <%= javascript_include_tag"js/jquery.js" %>

app/views/home/_header.html.erb
 <header id="header" class="fixx"><!--header-->
   <span >
    <% if notice %> 
      <p class="alert alert-success alrt"><%= notice %></p>
    <% end %>``
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  </span>
  <div class="header-middle"><!--header-middle-->
    <div class="row row-margin">
      <div class="col-sm-4">
        <div class="logo pull-left">
          <%= link_to root_path do%><%= image_tag("home/logo.png", alt: "") %><% end %>
        </div>
      </div>
      <div class="col-sm-8">
        <div class="shop-menu pull-right">
          <ul class="nav navbar-nav navbar-collapse">
            <li><%= link_to profile_index_path do%><%=image_tag("social/account.jpeg",class:"account-icon")%><span>Account</span><%end%>
              <ul role="menu" class="sub-menu">
                <li><%= link_to "Track Order", track_orders_path,:class=>"hee" %></li>
                <li><%= link_to "My order", orders_path,:class=>"hee" %></li>
              </ul>
            </li>
            <li><%= link_to wishlist_index_path do%><%= image_tag("social/wishh.png",class:"wishlist-icon", alt: "Wishlist") %>Wishlist<%end%></li>
              <% if user_signed_in? && @cart_products.size != 0 %>
            <li><%= link_to carts_path do%><%= image_tag("social/cart.png",class:"cart-icon", alt: "")%>Cart(<%=@cart_products.size%>)</li><% end %>
            <% else %>
            <li><%= link_to carts_path do%><%= image_tag("social/cart.png",class:"cart-icon", alt: "")%>Cart</li><%end%>
            <%end%>
            <% if user_signed_in? %>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %><li>
            <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div><!--/header-middle-->
  <div class="header-bottom"><!--header-bottom-->
    <div class="row">
      <div class="col-sm-9">
        <div class="mainmenu pull-left">
          <ul class="nav navbar-nav navbar-collapse">
            <li><%= link_to "Home", root_path %></li>
            <li class="dropdown"><%= link_to "Shop", products_path %></li> 
            <li><%= link_to "Blog",blogs_path %></li>
            <li><%= link_to "Contact",contacts_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div><!--/header-bottom-->
</header><!--/header-->

app/views/home/home.html.erb
<body>
  <section id="slider "><!--slider-->
    <div class="container hey">
      <div class="row">
        <div class="col-sm-12">
          <div id="slider-carousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
              <li data-target="#slider-carousel" data-slide-to="1"></li>
              <li data-target="#slider-carousel" data-slide-to="2"></li>
            </ol>
            <% if @banners.any? %>
              <% @banners.each do |post| %>
            <div >
              <div class="item active">
                <div class="col-sm-6">
                  <h1><span>E</span>-SHOPPER</h1>
                  <h2> Ecommerce Website</h2>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                </div>
                <div class="col-sm-6">
                  <%= image_tag post.image,class:"banner"  %>
                  <%= image_tag("home/pricing.png",class:"thumb") %>  
                </div>
                <% end %>
                <% end %>
              </div>
            </div>
            <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
              <i class="fa fa-angle-left"></i>
            </a>
            <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
              <i class="fa fa-angle-right"></i>
            </a> 
          </div>
        </div>
      </div>
    </div>
  </section><!--/slider-->
  <section>
    <div class="container">
      <div class="row">
        <div class="col-sm-3">
          <div class="left-sidebar">
            <h2>Categories</h2>
            <% @category.each do |cat| %>
            <% subcat = cat.subcategories %>
            <div class="panel-group category-products" ><!--category-productsr-->
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordian" href="#<%= cat.name %>">
                      <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                      <h2><%= cat.name %></h2>
                    </a>
                  </h4>
                </div>
                <div id="<%= cat.name %>" class="panel-collapse collapse">
                  <div class="panel-body">
                      <% subcat.each do |subc| %>
                    <ul>
                    <li><h4 style="margin-left:60px"><%= link_to subc.name,category_path(subc) %></h4></li>
                    </ul>
                    <%end%>
                  </div>
                </div>
              </div>
            </div><!--/category-products-->
            <% end %>
            </div>
          </div>
          <div class="col-sm-9 padding-right">
          <div class="features_items"><!--features_items-->
            <h2 class="title text-center">Features Items</h2>
            <% if @products.present? %>
              <% @products.each do |prod| %>
            <div class="col-sm-4">
              <div class="product-image-wrapper">
                <div class="productinfo text-center">
                  <%= link_to product_path(prod) do%><%= image_tag(prod.product_images.first.image) %>
                  <% end %>
                  <h2>$<%= prod.price %></h2>
                  <p><%= prod.name %></p>
                  <p> <%= prod.short_description %></p>
                  </div>
                  <%= link_to carts_path(id: prod),method: :post do%><%= image_tag("social/cart.png",class:"iconss", alt: "")%>
                  <%= link_to wishlist_index_path(id: prod),method: :post do%><%= image_tag("social/wishh.png",class:"icons", alt: "") %>
                  <div class="choose">
                    <%end %>
                  <% end %>
                </div>
              </div>
            </div>
            <% end %>
            <% end %>
            <button style="margin-top:600px;background-color: orange;position: absolute;"><%= link_to ">>", products_path %></button>
          </div>
        </div>
      </div>
    </div>
  </section>
<script>
  function myFunction() {
  var x = document.getElementById("myDIV");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
  }
</script>
</body>
</html>

app/views/home/index.html.erb
<br><br><br>
<% if user_signed_in? %>
  <%= link_to('Edit registration', edit_user_registration_path) %>
  <%= button_to('Logout', destroy_user_session_path, :method => :delete) %>
  <% if can? :manage, :dashboard %>
    <%= link_to('Admin Panel', rails_admin.dashboard_path) %>
  <% end %>
<% else %>
  <%= link_to('Register', new_user_registration_path)  %>
  <%= link_to('Login', new_user_session_path)  %>
<% end %>

app/views/home/show.html.erb
  <section id="slider " class="main-page-padding"><!--slider-->
      <div class="row">
        <div class="col-sm-12">
            <% if @banners.any? %>
              <% @banners.each do |post| %>
            <div >
              <div class="item active">
                <div class="col-sm-6">
                  <h1><span>E</span>-SHOPPER</h1>
                  <h2> Ecommerce Website</h2>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                </div>
                <div class="col-sm-6">
                  <%= image_tag post.image,class:"banner"  %>
                  <%= image_tag("home/pricing.png",class:"thumb") %>  
                </div>
                <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section><!--/slider-->
  <section>
      <div class="row">
        <div class="col-sm-3">
          <div class="left-sidebar">
            <h2>Categories</h2>
            <% @category.each do |cat| %>
            <% subcat = cat.subcategories %>
            <div class="panel-group category-products" ><!--category-productsr-->
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordian" href="#<%= cat.name %>">
                      <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                      <h2><%= cat.name %><span><%= image_tag("social/drop.png", class:"sidebar-dropdown") %> </span></h2>
                    </a>
                  </h4>
                </div>
                <div id="<%= cat.name %>" class="panel-collapse collapse">
                  <div class="panel-body subcat-panel">
                      <% subcat.each do |subc| %>
                    <ul>
                    <li><h4 class="productbtn"><%= link_to subc.name,category_path(subc) %></h4></li>
                    </ul>
                    <%end%>
                  </div>
                </div>
              </div>
            </div><!--/category-products-->
            <% end %>
            </div>
          </div>
          <div class="col-sm-9 padding-right">
          <div class="features_items"><!--features_items-->
            <h2 class="title text-center">Features Items</h2>
            <% if @products.present? %>
              <% @products.each do |prod| %>
            <div class="col-sm-4">
              <div class="product-image-wrapper">
                <div class="productinfo text-center">
                  <%= link_to product_path(prod) do%><%= image_tag(prod.product_images.first.image) %>
                  <% end %>
                  <h2>
                    <span class="price-symbol">₹</span><%= prod.price.to_i %></h2>
                  <p><%= prod.name %></p>
                  <p> <%= prod.short_description %></p>
                  </div>
                  <%= link_to carts_path(id: prod),method: :post do%><%= image_tag("social/cart.png",class:"iconss", alt: "")%>
                  <%= link_to wishlist_index_path(id: prod),method: :post do%><%= image_tag("social/wishh.png",class:"icons", alt: "") %>
                  <div class="choose">
                    <%end %>
                  <% end %>
                </div>
              </div>
            </div>
            <% end %>
            <% end %>
              <!-- <button class="more-prod-btn"><%= link_to "more", products_path %></button> -->
          </div>
        </div>
      </div>
  </section>
</div>
<script>
  function myFunction() {
  var x = document.getElementById("myDIV");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
  }
</script>
</body>
</html>