config/routes.rb
Rails.application.routes.draw do
  root 'home#show'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  
  resources :coupons

  resources :blogs

  resources :contacts

  resources :checkout

  resources :profile 


  resources :users do
    collection do
      post 'subscribe'
    end
  end

  resources :wishlist

  resources :categories

   resources :carts do
    member do
      post 'add' => "carts#add_quantity", as: "add_quantity"
      post 'minus' => "carts#dec_quantity", as: "dec_quantity"
    end
  end

  resources :addresses

  resources :orders do
    collection do
      post 'track'
    end
  end

  resources :home 
  
  resources :payment do
    collection do
      post 'stripe_payment'
      get 'stripe_paymet_success'
      get 'cod'
    end
  end

  resources :products
  
  resources :shop

end
 

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.superadmin_role?
      can :manage, :all
      can :access, :rails_admin  # only admin can access Rails Admin
      can :manage, :dashboard    # allow access to dashboard
    end

    if user.supervisor_role?
      can :manage, User
      # Define abilities for the user here. For example:
      #   return unless user.present?
      #   can :read, :all
      #   return unless user.admin?
      #   can :manage, :all
      # The first argument to `can` is the action you are giving the user
      # permission to do.
      # If you pass :manage it will apply to every action. Other common actions
      # here are :read, :create, :update and :destroy.
      # The second argument is the resource the user can perform the action on.
      # If you pass :all it will apply to every resource. Otherwise pass a Ruby
      # class of the resource.
      # The third argument is an optional hash of conditions to further filter the
      # objects.
      # For example, here the user can only update published articles.
      #   can :update, Article, published: true
      # See the wiki for details:
      # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories, dependent: :destroy
  has_many :products, through: :product_categories, dependent: :destroy
  has_many :subcategories, class_name: 'Category', foreign_key: 'parent_id', dependent: :destroy
  belongs_to :parent_category, class_name: 'Category', optional: true
end

app/models/cm.rb
class Cm < ApplicationRecord
end

app/models/configuration.rb
class Configuration < ApplicationRecord
end

app/models/contact_u.rb
class ContactU < ApplicationRecord
  validates_presence_of :name, :message, :email
  validates :contact_no, presence: true, numericality: true, length: { minimum: 10, maximum: 12 }
  belongs_to :user
  after_save :contact_mail
  after_update :contact_update_mail
  def contact_mail
    UserMailer.contact_mail(self).deliver
  end

  def contact_update_mail
    UserMailer.contact_update_mail(self).deliver
  end
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  has_many :coupons_useds, dependent: :destroy
  has_many :users, through: :coupons_useds
end

app/models/coupons_used.rb
class CouponsUsed < ApplicationRecord
  belongs_to :user
  belongs_to :coupon
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :user_order
  belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_images, dependent: :destroy
  has_many :product_attribute_assocs, dependent: :destroy
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories, dependent: :destroy
  has_many :user_wish_lists, dependent: :destroy
  has_many :users, through: :user_wish_lists
  has_many :order_details, dependent: :destroy
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  has_one_attached :image
end

app/models/report.rb
class Report < ApplicationRecord
  def sales_report
    UserOrder.all.size
  end

  def customer_registered
    User.all.size
  end

  def coupons_used
    CouponsUsed.all.size
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, format: { with: /[a-z0-9]+@[a-z]+\.[a-z]{2,3}/, message: 'Please enter valid email' }
  after_create :welcome_send
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2 github]
  has_many :coupons_useds, dependent: :destroy
  has_many :user_addresses, dependent: :destroy
  has_many :contact_us, dependent: :destroy
  has_many :coupons, through: :coupons_useds, dependent: :destroy
  has_many :user_orders, dependent: :destroy
  has_many :user_wish_lists, dependent: :destroy
  has_many :products, through: :user_wish_lists

  def self.from_omniauth(response)
    User.find_or_create_by(uid: response[:uid], provider: response[:provider]) do |u|
      u.email = response[:info][:email]
      u.password = Devise.friendly_token[0, 20]
    end
  end

  def welcome_send
    UserMailer.welcome_send(self).deliver
    UserMailer.admin_mail(self).deliver
  end
end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  has_many :user_order
  belongs_to :user
end

app/models/user_order.rb
class UserOrder < ApplicationRecord
  after_update :status_mail
  belongs_to :user
  belongs_to :user_address
  has_many :order_details, dependent: :destroy
  has_many :products, through: :order_details
  enum status: { ordered: 0, shipped: 1, delivered: 2 }
  def status_mail
    if status == 'shipped' || status == 'delivered'
      UserMailer.status_mail(status).deliver
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # showing all values in cart
  def index
    calculated_total_cart_value
  end

  # add product in cart
  def create
    id = params[:id].to_i if params[:id].present?
    session[:cart] << id unless session[:cart].include?(id)
    redirect_to request.referrer, notice: 'Product added successfully in cart.'
  end

  # remove product from cart
  def destroy
    id = params[:id].to_i if params[:id].present?
    session[:cart].delete(id)
    redirect_to carts_path, notice: 'Product successfully removed from cart.'
  end

  def cart_total_product_value
    product_price_lists = []
    products = Product.find(session[:cart])
    products.each do |product|
      total = product.quantity * product.price
      product_price_lists << total
    end
    total_price = product_price_lists.inject { |sum, price| sum + price }
  end

  # cart Toatal,shipping_cost
  def calculated_total_cart_value
    total_price = cart_total_product_value
    shipping_total = shipping_charge(total_price)
    order_total = total_price + shipping_total if total_price.present?
    coupon = params[:coupon_off].to_i
    percentage_off = order_total * coupon / 100 if coupon.present? && order_total.present?
    coupon.positive? ? order_total -= percentage_off : order_total
    session[:totals] = order_total
    @cart_total = { total_price: total_price.to_i,
                    shipping_total: shipping_total.to_i,
                    order_total: order_total }
  end

  # shipping charges
  def shipping_charge(value)
    value < 500 ? 50 : 0 if value.present?
  end

  # increase the product quanitity in the cart
  def add_quantity
    @product = Product.find(params[:id]) if params[:id].present?
    @product.update(quantity: @product.quantity += 1)
    calculated_total_cart_value
  end

  # decrease the product quanitity in the cart
  def dec_quantity
    @product = Product.find(params[:id]) if params[:id].present?
    destroy if @product.quantity <= 1
    @product.update(quantity: @product.quantity -= 1)
    calculated_total_cart_value
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/add_quantity.js.erb
$("#target-for-change-<%= @product.id%>").val("<%= @product.quantity rescue 0 %>");
$("#target-for-total-<%= @product.id%>").html("<%= @product.quantity * @product.price rescue 0 %>");
$("#target-for-total-cart").html("<%= @cart_total[:total_price] %>");
$("#total-product-val").html("<%=@cart_total[:shipping_total]%>");
$("#finall-vall").html("<%= @cart_total[:order_total] %>");

app/views/carts/dec_quantity.js.erb
$("#target-for-change-<%= @product.id%>").val("<%= @product.quantity rescue 0 %>");
$("#target-for-total-<%= @product.id%>").html("<%= @product.quantity * @product.price rescue 0 %>");
$("#target-for-total-cart").html("<%= @cart_total[:total_price] %>");
$("#total-product-val").html("<%= @cart_total[:shipping_total] %>");
$("#finall-vall").html("<%= @cart_total[:order_total] %>");

app/views/carts/index.html.erb
<body>
	<section id="cart_items">
		<div class="container main-page-padding">
			<% if @cart_products.product.present? %>
			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Item</td>
							<td class="image">Product_Image</td>
							<td class="price">Price</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total</td>
							<td ></td>
						</tr>
					</thead>
					<tbody>
						<% @product_price_lists = [] %>
						<% @cart_products.each do |product| %>
							<tr>
								<td><h4 ><%= product.name %></h4> </td>
								<td><%= link_to product_path(product) do%><%= image_tag(product.product_images.first.image,class:"thumbnaill")%><%end%></td>
								<td class="cart_price"><p>₹<%= product.price.to_i %></p></td>
								<td class="quantity">
									<div class="cart_quantity_button">
									<%= link_to '+',add_quantity_cart_path(product), method: :post, :remote => true,class: 'btn primary quantity cart_quantity_up'%>	
									<input id="target-for-change-<%= product.id %>"class="cart_quantity_input", name="quantity"  value="<%= product.quantity %>"size="1">
									<%= link_to '-',dec_quantity_cart_path(product), method: :post,remote: true, class: 'btn primary cart_quantity_up' %>
									</div>
								</td>
								<td class="cart_total">
								<p id="target-for-total-<%= product.id%>">₹<%= tp = (product.price).to_i*(product.quantity).to_i %><p>
								</td>
								<td class="cart_delete"><br>
									<%=  button_to "X", cart_path(product), method: :delete,data: { confirm: "Are you sure?" }%>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</section>
	<section id="do_action">
		<div class="container">
			<div class="heading">
				<h3>What would you like to do next?</h3>
				<p>Choose if you have a discount code or reward points you want to use or would like to estimate your delivery cost.</p>
			</div>
			<%= render :partial => 'coupons/form' %>
			<div class="col-sm-6">
				<div class="total_area">
					<ul>
						<li> Cart Total Price<span id="target-for-total-cart">₹<%= @cart_total[:total_price] %> </span></li>
						<li>Shipping Cost<span id="total-product-val">₹<%= @cart_total[:shipping_total] %></span></li>
						<li>Total<span id="finall-vall">₹<%= @cart_total[:order_total].to_i %><span></li>
						<% if @f_value == 0 %>
							<br><h6 style="color:red"><%= "please add the product in cart" %></h6>
						<%else%>
							<span class="btn btn-default check_out" href=""><%= link_to "Checkout",checkout_index_path%></span>
						<%end%>
					</ul>
				</div>
				</div>
			</div>
		</div>
	</section>
	<%else%>
		<%= image_tag("social/emptycart.png",class:"emptycart")%>  <br>
 		<div class="cartbtn"><button><%= link_to"shop",root_path%></button>
	<%end%></div>
</body>
</html>